{% set version = "1.2.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-jsonify
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/jsonify_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/jsonify/jsonify_{{ version }}.tar.gz
  sha256: 3745e962592f021a3deaed8b2f6b99c4f7181f28e095300a96d1c2b08af4af2f

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-rcpp >=0.12.18           # [build_platform != target_platform]
    - r-rapidjsonr >=1.2.0       # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.12.18
    - r-rapidjsonr >=1.2.0
  run:
    - r-base
    - r-rcpp >=0.12.18
    - r-rapidjsonr >=1.2.0

test:
  commands:
    - $R -e "library('jsonify')"           # [not win]
    - "\"%R%\" -e \"library('jsonify')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=jsonify
  license: GPL-2.0-or-later
  summary: Conversions between 'R' objects and Javascript Object Notation (JSON) using the 'rapidjsonr' library <https://CRAN.R-project.org/package=rapidjsonr>.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: jsonify
# Type: Package
# Title: Convert Between 'R' Objects and Javascript Object Notation (JSON)
# Version: 1.1.1
# Date: 2020-03-14
# Authors@R: c( person("David", "Cooley", ,"dcooley@symbolix.com.au", role = c("aut", "cre")), person("Chris", "Muir", role = "ctb") )
# Description: Conversions between 'R' objects and Javascript Object Notation (JSON) using the 'rapidjsonr' library <https://CRAN.R-project.org/package=rapidjsonr>.
# License: GPL (>= 2)
# Depends: R (>= 3.3.0)
# SystemRequirements: C++11
# Imports: Rcpp (>= 0.12.18)
# LinkingTo: rapidjsonr (>= 1.2.0), Rcpp
# RoxygenNote: 7.0.2
# Suggests: covr, testthat, knitr, rmarkdown
# Encoding: UTF-8
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2020-03-14 07:14:05 UTC; dave
# Author: David Cooley [aut, cre], Chris Muir [ctb]
# Maintainer: David Cooley <dcooley@symbolix.com.au>
# Repository: CRAN
# Date/Publication: 2020-03-14 07:50:02 UTC
